<a href="https://colab.research.google.com/github/Kashishkewat/python_practice/blob/main/day31_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Accuracy and Confusion matrix**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files
uploaded=files.upload()

Saving heart.csv to heart.csv

In [3]:
df=pd.read_csv("heart.csv")

In [4]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [6]:
from sklearn.tree import DecisionTreeClassifier

In [8]:
clf1=DecisionTreeClassifier()
clf2=LogisticRegression()

In [9]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [10]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
#

In [11]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [12]:
print("accracy of logistic regression",accuracy_score(y_test,y_pred2))
print("accracy of descision trees",accuracy_score(y_test,y_pred1))

accracy of logistic regression 0.9016393442622951
accracy of descision trees 0.819672131147541

In [21]:
print("confusion matrix of logistic regression",confusion_matrix(y_test,y_pred2))

confusion matrix of logistic regression [[26  6]
 [ 0 29]]

In [13]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.89      0.75      0.81        32
           1       0.76      0.90      0.83        29

    accuracy                           0.82        61
   macro avg       0.83      0.82      0.82        61
weighted avg       0.83      0.82      0.82        61

In [14]:
from sklearn.datasets import load_iris

In [18]:
df1=load_iris()

In [20]:
df_iris = pd.DataFrame(df1.data, columns=df1.feature_names)
df_iris['target'] = df1.target
df_iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_train,X_test,y_train,y_test=train_test_split(df_iris.iloc[:,0:-1],df_iris.iloc[:,-1],test_size=0.2,random_state=2)

In [24]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
clf_iris1=DecisionTreeClassifier()
clf_iris2=LogisticRegression()

In [26]:
clf_iris1.fit(X_train,y_train)
clf_iris2.fit(X_train,y_train)

LogisticRegression()

In [27]:
y_pred3=clf_iris1.predict(X_test)
y_pred4=clf_iris2.predict(X_test)
#

In [28]:
print("accracy of logistic regression",accuracy_score(y_test,y_pred4))
print("accracy of descision trees",accuracy_score(y_test,y_pred3))

accracy of logistic regression 0.9666666666666667
accracy of descision trees 0.9333333333333333

In [29]:
print("confusion matrix of logistic regression",confusion_matrix(y_test,y_pred4))

confusion matrix of logistic regression [[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]

In [30]:
print(classification_report(y_test,y_pred4))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.88      0.93         8
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30