<a href="https://colab.research.google.com/github/Kashishkewat/python_practice/blob/main/day31_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Accuracy and Confusion matrix**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files
uploaded=files.upload()

Saving heart.csv to heart.csv

In [3]:
df=pd.read_csv("heart.csv")

In [4]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [6]:
from sklearn.tree import DecisionTreeClassifier

In [7]:
clf1=DecisionTreeClassifier()
clf2=LogisticRegression()

In [8]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [9]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
#

In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [11]:
print("accracy of logistic regression",accuracy_score(y_test,y_pred2))
print("accracy of descision trees",accuracy_score(y_test,y_pred1))

accracy of logistic regression 0.9016393442622951
accracy of descision trees 0.8524590163934426

In [12]:
print("confusion matrix of logistic regression",confusion_matrix(y_test,y_pred2))

confusion matrix of logistic regression [[26  6]
 [ 0 29]]

In [13]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.96      0.75      0.84        32
           1       0.78      0.97      0.86        29

    accuracy                           0.85        61
   macro avg       0.87      0.86      0.85        61
weighted avg       0.87      0.85      0.85        61

In [14]:
from sklearn.datasets import load_iris

In [15]:
df1=load_iris()

In [16]:
df_iris = pd.DataFrame(df1.data, columns=df1.feature_names)
df_iris['target'] = df1.target
df_iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_train,X_test,y_train,y_test=train_test_split(df_iris.iloc[:,0:-1],df_iris.iloc[:,-1],test_size=0.2,random_state=2)

In [18]:
from sklearn.tree import DecisionTreeClassifier

In [19]:
clf_iris1=DecisionTreeClassifier()
clf_iris2=LogisticRegression()

In [20]:
clf_iris1.fit(X_train,y_train)
clf_iris2.fit(X_train,y_train)

LogisticRegression()

In [21]:
y_pred3=clf_iris1.predict(X_test)
y_pred4=clf_iris2.predict(X_test)
#

In [22]:
print("accracy of logistic regression",accuracy_score(y_test,y_pred4))
print("accracy of descision trees",accuracy_score(y_test,y_pred3))

accracy of logistic regression 0.9666666666666667
accracy of descision trees 0.9333333333333333

In [23]:
print("confusion matrix of logistic regression",confusion_matrix(y_test,y_pred4))

confusion matrix of logistic regression [[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]

In [24]:
print(classification_report(y_test,y_pred4))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.88      0.93         8
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

# **Precision ,Recall and F1 Score**

In [25]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [26]:
cdf=pd.DataFrame(confusion_matrix(y_test,y_pred3),columns=list(range(0,3)))
print(cdf)

    0  1  2
0  14  0  0
1   0  7  1
2   0  1  7

In [27]:
print("precision-",precision_score(y_test,y_pred3, average='weighted'))
print("recall-",recall_score(y_test,y_pred3, average='weighted'))
print("f1 score-",f1_score(y_test,y_pred3, average='weighted'))

precision- 0.9333333333333333
recall- 0.9333333333333333
f1 score- 0.9333333333333333

# **how to calculate precision and recall in multi-class?**

In [29]:
from google.colab import files
uploaded=files.upload()

Saving train.csv to train.csv

In [30]:
df2=pd.read_csv("train.csv")

In [31]:
df2.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [36]:
X_train,X_test,y_train,y_test=train_test_split(df2.iloc[:,1:],df2.iloc[:,0],test_size=0.2,random_state=2)

In [34]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [37]:
model=LogisticRegression()
model.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [38]:
y_pred5=model.predict(X_test)
#

In [39]:
print("accracy of logistic regression",accuracy_score(y_test,y_pred5))

accracy of logistic regression 0.9145238095238095

In [41]:
print("confusion matrix of logistic regression",confusion_matrix(y_test,y_pred5))

confusion matrix of logistic regression [[791   0   1   0   1   9  11   1   6   1]
 [  0 938   2   4   0   3   0   3  12   0]
 [  2   9 745  16   9   4  13  13  15   3]
 [  1   4  19 763   0  36   5   5  20  11]
 [  2   5   4   0 804   1   7   3   9  21]
 [  9   3   4  23  10 610  15  10  34  11]
 [ 12   4  12   1   7   8 789   0   5   1]
 [  3   2  13   6   4   2   0 812   2  29]
 [ 11  12  13  18   1  21   6   6 694  11]
 [  3   6   2  14  25   4   0  37   7 736]]

In [43]:
print(precision_score(y_test,y_pred5,average=None))
print(recall_score(y_test,y_pred5,average=None))

[0.94844125 0.95422177 0.91411043 0.90295858 0.93379791 0.8739255
 0.93262411 0.91235955 0.86318408 0.89320388]
[0.9634592  0.97505198 0.8986731  0.88310185 0.93925234 0.83676269
 0.94040524 0.930126   0.87515763 0.882494  ]

In [46]:
print(f1_score(y_test,y_pred5,average=None))

[0.95589124 0.96452442 0.90632603 0.89291984 0.93651718 0.85494043
 0.93649852 0.92115712 0.86912962 0.88781665]

In [47]:
print(precision_score(y_test,y_pred5,average="macro"))#average of all precision
print(recall_score(y_test,y_pred5,average="macro"))
print(f1_score(y_test,y_pred5,average="macro"))

0.9128827064397905
0.9124484028871509
0.9125721045561427

In [48]:
print(precision_score(y_test,y_pred5,average="weighted"))
print(recall_score(y_test,y_pred5,average="weighted"))
print(f1_score(y_test,y_pred5,average="weighted"))

0.9142150713630827
0.9145238095238095
0.9142794994052751

In [40]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred5))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       821
           1       0.95      0.98      0.96       962
           2       0.91      0.90      0.91       829
           3       0.90      0.88      0.89       864
           4       0.93      0.94      0.94       856
           5       0.87      0.84      0.85       729
           6       0.93      0.94      0.94       839
           7       0.91      0.93      0.92       873
           8       0.86      0.88      0.87       793
           9       0.89      0.88      0.89       834

    accuracy                           0.91      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.91      0.91      0.91      8400