<a href="https://colab.research.google.com/github/Kashishkewat/python_practice/blob/main/day38_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **K-Nearest Neighbors (KNN)**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [12]:
from google.colab import files
uploaded=files.upload()

Saving train.csv to train (2).csv

In [16]:
df=pd.read_csv("train (2).csv")[["Age",'Fare','Pclass','Survived']]

In [17]:
df.head()

    Age     Fare  Pclass  Survived
0  22.0   7.2500       3         0
1  38.0  71.2833       1         1
2  26.0   7.9250       3         1
3  35.0  53.1000       1         1
4  35.0   8.0500       3         0

In [18]:
df.isnull().mean()*100

Age         19.86532
Fare         0.00000
Pclass       0.00000
Survived     0.00000
dtype: float64

In [19]:
X=df.drop(columns=['Survived'],axis=1)
y=df['Survived']

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [21]:
X_train.head()

      Age     Fare  Pclass
30   40.0  27.7208       1
10    4.0  16.7000       3
873  47.0   9.0000       3
182   9.0  31.3875       3
876  20.0   9.8458       3

In [28]:
knn=KNNImputer(n_neighbors=3)
X_train_trf=knn.fit_transform(X_train)
X_test_trf=knn.transform(X_test)

In [29]:
pd.DataFrame(X_train_trf,columns=X_train.columns)

           Age      Fare  Pclass
0    40.000000   27.7208     1.0
1     4.000000   16.7000     3.0
2    47.000000    9.0000     3.0
3     9.000000   31.3875     3.0
4    20.000000    9.8458     3.0
..         ...       ...     ...
707  30.000000    8.6625     3.0
708  26.000000    8.7125     3.0
709  71.000000   49.5042     1.0
710  32.666667  221.7792     1.0
711  53.333333   25.9250     1.0

[712 rows x 3 columns]

In [30]:
lr=LinearRegression()
lr.fit(X_train_trf,y_train)

LinearRegression()

In [31]:
y_pred=lr.predict(X_test_trf)
y_pred_binary = np.where(y_pred > 0.5, 1, 0)
accuracy_score(y_test,y_pred_binary)

0.7094972067039106

In [32]:
si=SimpleImputer()
X_train_trf2=si.fit_transform(X_train)
X_test_trf2=si.transform(X_test)

In [34]:
lr=LinearRegression()
lr.fit(X_train_trf2,y_train)

LinearRegression()

In [35]:
y_pred=lr.predict(X_test_trf2)
y_pred_binary1 = np.where(y_pred > 0.5, 1, 0)
accuracy_score(y_test,y_pred_binary1)

0.6871508379888268